### ISSUE TITLE
NoMethodError: undefined method `fetch_movie'

### ISSUE THREAD

**Issue by cnwilliams** [tmobaird/GuideboxWrapper#3]
Under the "Accessible Tv Attributes" example, you list 

`guidebox_tv = GuideboxWrapper::GuideboxTv.new("YOUR_API_KEY", "region")
show = guidebox_tv.fetch_movie("entourage")`

However,  `.fetch_movie` throws the error "NoMethodError: undefined method fetch_movie ".  It appears that `.fetch_tv_show` should be the method used in this example.

**Comment by tmobaird** [comment]
@cnwilliams you're totally right. Good catch! Did you want to submit a pull request that changes this?

**Comment by itroman** [comment]
I went ahead and submitted a pull request for this, as I saw it was still open.  Hope that's ok!

**Comment by tmobaird** [comment]
@itroman definitely! I appreciate the contribution. I'm actually hoping to revamp this project soon, feel free let me know if you'd like to help out with that!

**Comment by itroman** [comment]
@tmobaird no problem!  I'm definitely interested in helping out!  Let me know what needs doing.
